# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/2024CODH/labs/lab1/SRT_FPGAOL/SRT_FPGAOL.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
# IP: The module: 'dist_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/2024CODH/labs/lab1/SRT_FPGAOL/SRT_FPGAOL.gen/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Projects/2024CODH/labs/lab1/SRT_FPGAOL/SRT_FPGAOL.srcs/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1.xci
# IP: The module: 'dist_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/2024CODH/labs/lab1/SRT_FPGAOL/SRT_FPGAOL.gen/sources_1/ip/dist_mem_gen_1/dist_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
