# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/2024CODH/labs/lab4/sorting_env/run_vivado/CPU_SRT/CPU_SRT.srcs/sources_1/ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/2024CODH/labs/lab4/sorting_env/run_vivado/CPU_SRT/CPU_SRT.gen/sources_1/ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Projects/2024CODH/labs/lab4/sorting_env/run_vivado/CPU_SRT/CPU_SRT.srcs/sources_1/ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/2024CODH/labs/lab4/sorting_env/run_vivado/CPU_SRT/CPU_SRT.gen/sources_1/ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
