# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/2024CODH/labs/lab1/SRT/SRT.srcs/sources_1/ip/RAM_dist/RAM_dist.xci
# IP: The module: 'RAM_dist' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/2024CODH/labs/lab1/SRT/SRT.gen/sources_1/ip/RAM_dist/RAM_dist_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_dist'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Projects/2024CODH/labs/lab1/SRT/SRT.srcs/sources_1/ip/RAM_dist/RAM_dist.xci
# IP: The module: 'RAM_dist' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/2024CODH/labs/lab1/SRT/SRT.gen/sources_1/ip/RAM_dist/RAM_dist_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_dist'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
